swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
x-swagger-mongoose:
  json-api: true
  key-conversion: camelcase
  schema-options:
    timestamps: true
paths:
  /hello:
    x-swagger-router-controller: hello-world
    get:
      description: Returns 'Hello' to the caller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

  /people:
    x-swagger-router-controller: person-controller
    get:
      operationId: index
      summary: Gets all people
      description: Returns a list containing all people.
      responses:
        200:
          description: A list of Person
          schema:
            type: object
            additionalProperties: false
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Person"
    post:
      summary: Creates a person
      description: Adds a new person to the people list.
      parameters:
        - name: person
          in: body
          description: The person data.
          required: true
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Person"
      responses:
        201:
          description: people succesfully created.
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Person"
        400:
          description: people could not be created.
  /people/{id}:
    x-swagger-router-controller: person-controller
    get:
      summary: Gets a person
      description: Returns a single person by identifier.
      parameters:
        - name: id
          in: path
          required: true
          description: The person's id
          type: string
      responses:
        200:
          description: A Person
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Person"
        404:
          description: The person does not exist
  /edges:
    x-swagger-router-controller: edge-controller
    get:
      operationId: index
      summary: Gets all edges
      description: Returns a list containing all edges.
      responses:
        200:
          description: A list of Edges
          schema:
            type: object
            additionalProperties: false
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Edge"
    post:
      summary: Creates an edge
      description: Adds a new edge to the edge list.
      parameters:
        - in: body
          name: edge
          description: the edge data.
          required: true
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Edge"
      responses:
        201:
          description: Edge successfully created.
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Edge"
        400:
          description: Edge could not be created.
  /edges/{id}:
    x-swagger-router-controller: edge-controller
    get:
      summary: Gets an edge
      description: Returns a single edge by its identifier.
      parameters:
        - in: path
          name: id
          required: true
          description: the edge's id
          type: string
      responses:
        200:
          description: An edge
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Edge"
        404:
          description: The edge does not exist

  /nodes:
    x-swagger-router-controller: node-controller
    get:
      operationId: index
      summary: Gets all Nodes
      description: Returns a list containin all nodes
      responses:
        200:
          description: A list of Nodes
          schema:
            type: object
            additionalProperties: false
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Node"
    post:
      summary: Creates a node
      description: Adds a new node to the node list.
      parameters:
        - in: body
          name: node
          description: the node data.
          required: true
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Node"
      responses:
        201:
          description: Node successfully created.
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Edge"
        400:
          description: Node could not be created.
  /nodes/{id}:
    x-swagger-router-controller: node-controller
    get:
      summary: Gets a node
      description: Returns a single node by its identifier.
      parameters:
        - in: path
          name: id
          required: true
          description: the node's id
          type: string
      responses:
        200:
          description: A node
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Edge"
        404:
          description: The node does not exist


definitions:
  Person:
    type: object
    required:
      - type
      - attributes
    properties:
      type:
        type: string
      id:
        type: string
      attributes:
        type: object
        required:
          - username
        properties:
          username:
            type: string
          firstName:
            type: string
          lastName:
            type: string
  Edge:
    type: object
    required:
      - type
      - attributes
    properties:
      type:
        type: string
      id:
        type: string
      attributes:
        type: object
        properties:
          title:
            type: string
      relationships:
        type: object
        properties:
          source:
            type: string
            x-swagger-mongoose:
              $ref: "#/definitions/Node"
          target:
            type: string
            x-swagger-mongoose:
              $ref: "#/definitions/Node"
  Node:
    type: object
    required:
      - type
      - attributes
    properties:
      type:
        type: string
      id:
        type: string
      attributes:
        type: object
        properties:
          title:
            type: string
          events:
            type: array
            items:
              type: string
          position:
            type: array
            items:
              type: number
              format: float
              minItems: 2
              maxItems: 2
      relationships:
        type: object
        properties:
          outgoing:
            type: array
            items:
              type: string
              x-swagger-mongoose:
                $ref: "#/definitions/Node"
          incoming:
            type: array
            items:
              type: string
              x-swagger-mongoose:
                $ref: "#/definitions/Node"
  HelloWorldResponse:
    x-swagger-mongoose:
      exclude-schema: true
    type: object
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    x-swagger-mongoose:
      exclude-schema: true
    type: object
    required:
      - message
    properties:
      message:
        type: string
